### ISSUE TITLE
V2.0 doesn't work with jsConnect plugin 1.5.3

### ISSUE THREAD

**Issue by VeeK727** [vanilla/jsConnectPHP#12]
I see that a lot of `$_GET` parameter names have been changed like `client_id` to `v` and `signature` to `sig`. There have not been similar changes to the plugin so this file isn't working with the plugin. Are you planning to update the plugin as well? Should I use the older version of functions file till then?

**Comment by DaazKu** [comment]
If you want to use jsConnect v2 you have to use the jsConnect plugin >= v1.5.4

https://github.com/vanilla/addons/tree/master/plugins/jsconnect

The current version is 1.5.5

**Comment by DaazKu** [comment]
I made the version 1.5.4 available on the community site https://open.vanillaforums.com/addon/jsconnect-plugin-1.5.4
