### ISSUE TITLE
Appropriate jsConnect version for Vanilla 3.3 

### ISSUE THREAD

**Issue by Koenvh1** [vanilla/jsConnectPHP#20]
I noticed that this library has been updated to the jsConnect v3 protocol. However, the Vanilla jsConnect plugin does not seem to support it yet (at least v1.6 from https://open.vanillaforums.com/addon/jsconnect-plugin). 

![afbeelding](https://user-images.githubusercontent.com/5168825/82957169-b05b7400-9fb2-11ea-9b34-1639f04debde.png)

The one from https://github.com/vanilla/addons does support v3, but does not support the latest Vanilla Forums v3.3 release (https://open.vanillaforums.com/addon/vanilla-core), as it relies on SSOAddon that was only added in https://github.com/vanilla/vanilla/commit/f7a60405cadf6110d6b4b0c6af85dfe433cc8305#diff-91240f82b31731bbfa1a1cbe10eea7e7. 

Is there a stable Vanilla jsConnect plugin that does work for v3.3 and supports the v3 protocol? Or what is the recommended course of action?

**Comment by bayview** [comment]
I too have trouble getting Vanilla 3.3, jsConnect 1.6 or the github version, and jsConnectPHP v3.0 to work together.

I get "Missing field: querystring[jwt]".

Any progress on this?

**Comment by Koenvh1** [comment]
The old functional style still supports v2, so for the time being, that's what I'm using.

**Comment by charrondev** [comment]
Vanilla's JSConnect addon ships directly from Vanilla, and not in another repository. https://github.com/vanilla/vanilla/tree/master/plugins/jsconnect
