### ISSUE TITLE
JsHash for sha1

### ISSUE THREAD

**Issue by bls20Automic** [vanilla/jsConnectPHP#5]
Forgive me if im wrong, but if i were to set secure method to sha1,  the JsHash() switch statement would never reach case 'sha1' because  the previous case check "case : TRUE"  will resolve first.  This means the hash will be md5 secured and not sha1, thus producing an in valid signature.  I had to remove the case true: test in order to turn on sha1.

**Comment by keenly** [comment]
fixed by tburry here: https://github.com/vanilla/jsConnectPHP/commit/1cea0758b56f09867de4687e17bf1f04e79f5d0a#diff-6fe2b5baa4c512a1a667978b960ebe98
